### PR TITLE
Update ball_bin example to use a blend file

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
~\CC @zachfang FYI.  This was something I was playing with a few weeks ago.  I've rebased it now, but haven't tried re-running it.  I assume something is still broken.~

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12)* status: 1 unresolved discussion, needs at least one assigned reviewer

___
*[`examples/ball_bin.py` line 180 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NU-7BgW1AR6iuZW3XHx:-NU-7BgXCx5QkFQIFDrX:b-l1zy4k) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/d03ad37f3db3a855094afd2822cf6e5df4d45edd/examples/ball_bin.py#L180)):*
> ```Python
>             # TODO(jwnimmer-tri) Add this back somehow. At the moment, it
>             # messes up the camera and/or lighting somehow.
>             # f"--blend_file={blend_file}",
> ```

If you uncomment this line, you can see the failure(s).

**Comment by zachfang** [comment]
From a quick experiment, it seems like a (unknown) problem with that specific blend file. I can load the blend file we have been using.

```
Read blend: /home/zachfang/drake-blender/template_scene_tri_logo.blend
Data are loaded, start creating Blender stuff
glTF import finished in 0.05s
Fra:1 Mem:44.12M (Peak 44.14M) | Time:00:00.00 | Syncing Spot
Fra:1 Mem:44.12M (Peak 44.14M) | Time:00:00.00 | Syncing tri_logo  -> The model in the blend file.
Fra:1 Mem:52.31M (Peak 56.15M) | Time:00:00.03 | Syncing Renderer Node
Fra:1 Mem:52.32M (Peak 56.15M) | Time:00:00.03 | Syncing mesh0
Fra:1 Mem:52.86M (Peak 56.15M) | Time:00:00.03 | Syncing mesh1
Fra:1 Mem:53.40M (Peak 56.15M) | Time:00:00.03 | Syncing mesh2
Fra:1 Mem:53.94M (Peak 56.15M) | Time:00:00.03 | Syncing mesh3
Fra:1 Mem:54.49M (Peak 56.15M) | Time:00:00.04 | Syncing mesh4
Fra:1 Mem:55.03M (Peak 56.15M) | Time:00:00.04 | Syncing mesh5
Fra:1 Mem:55.04M (Peak 56.15M) | Time:00:00.04 | Syncing mesh6
Fra:1 Mem:55.05M (Peak 56.15M) | Time:00:00.04 | Syncing mesh7
Fra:1 Mem:55.59M (Peak 56.15M) | Time:00:00.04 | Syncing mesh8
Fra:1 Mem:55.60M (Peak 56.15M) | Time:00:00.04 | Syncing mesh9
Fra:1 Mem:55.61M (Peak 56.15M) | Time:00:00.04 | Syncing mesh10
Fra:1 Mem:56.15M (Peak 56.17M) | Time:00:00.04 | Syncing mesh11
Fra:1 Mem:56.16M (Peak 56.21M) | Time:00:00.04 | Syncing mesh12
Fra:1 Mem:56.17M (Peak 56.22M) | Time:00:00.04 | Syncing mesh13
Fra:1 Mem:56.71M (Peak 56.73M) | Time:00:00.04 | Syncing Camera Node
Fra:1 Mem:56.68M (Peak 56.73M) | Time:00:00.04 | Rendering 1 / 65 samples
Fra:1 Mem:52.89M (Peak 56.73M) | Time:00:00.07 | Rendering 26 / 64 samples
Fra:1 Mem:52.89M (Peak 56.73M) | Time:00:00.10 | Rendering 51 / 64 samples
Fra:1 Mem:52.89M (Peak 56.73M) | Time:00:00.11 | Rendering 64 / 64 samples
Saved: '/tmp/drake_render_gltf_blender_w0prmh83/2023-04-26_22-05-11-305282.png'
 Time: 00:00.23 (Saving: 00:00.09)
```

Let me correctly render the models in the blend file into the image/video to confirm.

**Comment by zachfang** [comment]
Confirmed that we can load our blend file containing a model and a spotlight with the existing code.

blender_camera

**Comment by jwnimmer-tri** [comment]
So what might make the most sense is to focus on #4 next.  If we have a unit test that actually checks the rendered image against a goal image, that would be a huge leg up for future changes and debugging.

**Comment by jwnimmer-tri** [comment]
I just rebased.  I still see `RuntimeError: RenderClient: expected to import (width=1024,height=1024) from the file '0000000000000000001-color.png', but got (width=2048,height=2048).`  So whatever thing in the sample blend file that screws up image sizes is still happening.

**Comment by jwnimmer-tri** [comment]
Aha.  `scene.render.resolution_percentage = 100`.  (It was 200.)  I'll push an update shortly.

**Comment by jwnimmer-tri** [comment]
I've pushed an update.  Nothing crashes anymore, but the color `png` returned by the server is 100% transparent.  I'll see if I can figure out what's wrong, but we might need to call some help.

**Comment by jwnimmer-tri** [comment]
No dice yet.  I found some `render.settings` differences (most notable, CYCLES vs EEVEE) but even resetting those didn't fix it:
```
        scene.render.engine = "BLENDER_EEVEE"
        scene.render.use_single_layer = False
        scene.render.use_compositing = True
        scene.render.simplify_subdivision_render = 6
        scene.render.image_settings.exr_codec = "ZIP"
```

**Comment by jwnimmer-tri** [comment]
Okay, well, other demo files work:
image

I'll just find a good one to switch to instead of `diorama` for now.  We can debug that later.

**Comment by jwnimmer-tri** [comment]
@zachfang Any opinions on this as a demo video for this repo?  It uses ["Sculpt mode painting"](https://www.blender.org/download/demo-files/#painting) blend file.

https://github.com/RobotLocomotion/drake-blender/assets/17596505/770f7b06-8c24-4ac4-9aaa-5a6707f75718

I guess I could move the camera maybe 30% closer, maybe drop the balls from a little bit higher, and raise the bin above the cloth (a few inches).

The rendering is approximately 12 seconds per frame (x 24 frames), so approx 5 minutes to render.  We could adjust that as well.

**Comment by jwnimmer-tri** [comment]
Okay, I'm pretty happy with this one:

https://github.com/RobotLocomotion/drake-blender/assets/17596505/c0f5f6ae-db51-42cb-9a86-09fa1c9ae18e

I've pushed the code for that now.  I need to fix some logging and tmpdir stuff, and then this should be ready for review.

**Comment by zachfang** [comment]
Wow, this looks super cool visually!

**Comment by jwnimmer-tri** [comment]
I have a big wishlist for improving the examples, but I have to stop and checkpoint somewhere.  I think this is probably a good place, so +@zachfang for review, please.

**Review by zachfang — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r4, 3 of 5 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-:-NVATdBjAXjeFZsf5z_I:bnfp4nl)* status: 7 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`README.md` line 34 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVALVn654rKjC5louA9:-NVALVn7EnSqcqq51Tpo:b-dhj9qx) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/d2038e7f8164d430dab0dd6080470d4d286059e2/README.md#L34)):*
> ```Markdown
> ```
> 
> Note that `server.py` is self contained. Instead of using Bazel, you can also
> ```

nit. self-contained?



_Code quote:_
```Markdown
self contained
```
___
*[`WORKSPACE.bazel` line 49 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVALkYZ2geZkXYeQVQK:-NVALkYZ2geZkXYeQVQL:bb7lc56) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/d2038e7f8164d430dab0dd6080470d4d286059e2/WORKSPACE.bazel#L49)):*
> ```Starlark
> install_deps()
> 
> # This is sample artwork from https://www.blender.org/download/demo-files/,
> ```

nit.



_Suggestion:_
```Starlark
This is a sample artwork
```
___
*[`WORKSPACE.bazel` line 59 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVALwOXDP94ZSMiltk2:-NVALwOXDP94ZSMiltk3:bdzqbli) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/d2038e7f8164d430dab0dd6080470d4d286059e2/WORKSPACE.bazel#L59)):*
> ```Starlark
>             "https://mirrors.ocf.berkeley.edu/blender",
>             "https://mirror.clarkson.edu/blender",
>         ]
> ```

BTW/question. Does this spelling mean Bazel will try to fetch the blend file from either place?



_Code quote:_
```Starlark
        for base in [
            "https://mirrors.ocf.berkeley.edu/blender",
            "https://mirror.clarkson.edu/blender",
        ]
```
___
*[`examples/ball_bin.py` line 195 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVATJUODYzUUz-hDico:-NVATJUODYzUUz-hDicp:b8i7v1q) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/d2038e7f8164d430dab0dd6080470d4d286059e2/examples/ball_bin.py#L195)):*
> ```Python
>         ], stdout=log_file, stderr=subprocess.STDOUT)
>         # Wait until the server is ready.
>         while True:
> ```

BTW. Do we want to set a time-bound here?



_Code quote:_
```Python
while True:
```
___
*[`examples/README.md` line 24 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVAPYSr2Fh8qbRilMqn:-NVAPYSr2Fh8qbRilMqo:b-24tse8) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/d2038e7f8164d430dab0dd6080470d4d286059e2/examples/README.md#L24)):*
> ```Markdown
> ```
> 
> This will create a videos named blender_camera.mp4 and vtk_camera.mp4.
> ```

BTW. Should we mention that anything loaded via a blend file will not appear in the VTK renderings? It didn't occur to me right away when I was debugging the blend file loading.
___
*[`examples/README.md` line 33 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVAPyk5B1FEvYZJYhah:-NVAPyk5B1FEvYZJYhai:b9jt801) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/d2038e7f8164d430dab0dd6080470d4d286059e2/examples/README.md#L33)):*
> ```Markdown
> ```
> 
> Thanks to Ramil Roosileht (https://twitter.com/limarest_art) for creating
> ```

BTW. Does that count as a contributor for the project (mainly asking, I don't know)?



_Code quote:_
```Markdown
Thanks to Ramil Roosileht
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12)* status: 2 unresolved discussions (waiting on @jwnimmer-tri and @zachfang)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVAY6WS2tZBzik53sKF:-NVAY6WS2tZBzik53sKG:b-oomlyv) (no related file):*
Working

I can reproduce the CI timeout locally.  I think blender is falling back to software rendering which takes too many cpu-minutes, especially on a low-core-count machine.

___
___
*[`WORKSPACE.bazel` line 59 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVALwOXDP94ZSMiltk2:-NVAVfM3CCe_miQml_WV:b-t0lvvx) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/d2038e7f8164d430dab0dd6080470d4d286059e2/WORKSPACE.bazel#L59)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW/question. Does this spelling mean Bazel will try to fetch the blend file from either place?
</blockquote></details>

Yes, for `urls = [...]` means that all of the items in the list should be identical downloads (all have the same checksum), so in case one server is down it can still use the other one.
___
*[`examples/ball_bin.py` line 195 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVATJUODYzUUz-hDico:-NVAVPlE9irjvAJIFse7:b6fj3b6) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/d2038e7f8164d430dab0dd6080470d4d286059e2/examples/ball_bin.py#L195)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Do we want to set a time-bound here?
</blockquote></details>

I was OK letting the user decide to Ctrl-C, per their own taste.  If the server crashes, the code here does notice and immediately return.
___
*[`examples/README.md` line 33 at r6](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVAPyk5B1FEvYZJYhah:-NVAUy8m2MJ4sKSZdgXi:bmyxck5) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/d2038e7f8164d430dab0dd6080470d4d286059e2/examples/README.md#L33)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Does that count as a contributor for the project (mainly asking, I don't know)?
</blockquote></details>

To me at least, crediting in the examples-specific README is more sensible than the top-level one.

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 5 files at r5, 3 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
You don't need to review the temporary server changes here, they will be rebased away.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-:-NVB4awO9jqX9GCEFwAD:b-uajo5a)* status: 1 unresolved discussion (waiting on @jwnimmer-tri and @zachfang)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-NVAY6WS2tZBzik53sKF:-NVB4UCF0qJEcNsusJIM:b-n6sw2) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

I can reproduce the CI timeout locally.  I think blender is falling back to software rendering which takes too many cpu-minutes, especially on a low-core-count machine.
</blockquote></details>

I think I have this fixed now.  I've filed a separate PR with the settings feature, and temporarily cherry-picked that here to see if CI passes.

___

**Review by zachfang — COMMENTED** [review]
I think I have reviewed all the latest changes minus the bpy setting part.

> Reviewed 3 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-:-NVBSFKVAo16Kf_VK-8H:bk11kgx)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Rebased now.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-:-NVBVoas7jQEznF-t_zp:b-y6051f)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang (waiting on @zachfang)

**Comment by jwnimmer-tri** [comment]
In reviewable, r7..r9 span will show the changes related to the CYCLES fixup.

**Review by zachfang — COMMENTED** [review]
:lgtm: again to be explicit.

> Reviewed 1 of 6 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/12#-:-NVBWNx9Blu6HmvhQ2VB:b-dhe54d)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang (waiting on @jwnimmer-tri)

**Pull request merged**
