### PR TITLE
Add example demo

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #5.

This does not yet load a `*.blend` file.  That will be future work under #5.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri (waiting on @jwnimmer-tri)

___
*[`examples/ball_bin.py` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9#-NSgTQKJ2ZiNiN2QIYrj:-NSgTQKJ2ZiNiN2QIYrk:b-g7voyd) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/c0fccefcaca698bdef841a5ec41263a94fc56568/examples/ball_bin.py#L17)):*
> ```Python
> 
> from bazel_tools.tools.python.runfiles import runfiles
> import tqdm
> ```

nit It wasn't clear to me how to satisfy this dependency, since bazel isn't doing it. I ended up doing terrible `pip` things. Is there a recommended way to satisfy the `requirements.txt` dependencies?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri (waiting on @rpoyner-tri)

___
*[`examples/ball_bin.py` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9#-NSgTQKJ2ZiNiN2QIYrj:-NSgVYy85cWj7AtJT0WI:b-ps5jdg) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/c0fccefcaca698bdef841a5ec41263a94fc56568/examples/ball_bin.py#L17)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit It wasn't clear to me how to satisfy this dependency, since bazel isn't doing it. I ended up doing terrible `pip` things. Is there a recommended way to satisfy the `requirements.txt` dependencies?
</blockquote></details>

Bazel _should_ have been doing it.  You can DM me to co-debug if you like.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9#-NSgXdyOEflcmM6tPJk0:-NSgXdyOEflcmM6tPJk1:b1xdkku) (no related file):*
Working

Add CI smoke test of the example.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9)* status: 2 unresolved discussions, LGTM missing from assignee rpoyner-tri (waiting on @jwnimmer-tri)

___
*[`examples/ball_bin.py` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9#-NSgTQKJ2ZiNiN2QIYrj:-NSg_l116ZMeCwnF5sQE:b-nzu6gp) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/c0fccefcaca698bdef841a5ec41263a94fc56568/examples/ball_bin.py#L17)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

from DMs: some work is still needed here.
</blockquote></details>

I forgot a deps.  I'll push it with the CI test (after meetings):

```patch
--- a/examples/BUILD.bazel
+++ b/examples/BUILD.bazel
@@ -10,6 +10,7 @@ py_binary(
     srcs = ["ball_bin.py"],
     deps = [
         "@examples_requirements_drake//:pkg",
+        "@examples_requirements_tqdm//:pkg",
     ],
     data = [
         ":ball_bin.yaml",
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri (waiting on @jwnimmer-tri and @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9#-NSgXdyOEflcmM6tPJk0:-NSgoZdp77qRVG69hTTU:b-fxvkn6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Add CI smoke test of the example.
</blockquote></details>

Working

Add xvfb to CI.

___
___
*[`examples/ball_bin.py` line 17 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9#-NSgTQKJ2ZiNiN2QIYrj:-NSgodNgCdGtBcSlDlfy:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/c0fccefcaca698bdef841a5ec41263a94fc56568/examples/ball_bin.py#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I forgot a deps.  I'll push it with the CI test (after meetings):

```patch
--- a/examples/BUILD.bazel
+++ b/examples/BUILD.bazel
@@ -10,6 +10,7 @@ py_binary(
     srcs = ["ball_bin.py"],
     deps = [
         "@examples_requirements_drake//:pkg",
+        "@examples_requirements_tqdm//:pkg",
     ],
     data = [
         ":ball_bin.yaml",
```
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9#-NSgXdyOEflcmM6tPJk0:-NSkoz7u7d8BDH9Oj0fr:bcyj5ff) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

Add xvfb to CI.
</blockquote></details>

I'm testing this in #10 but I'm struggling with what appears to be X protocol version shear.

One option would be to mark the regression test `tags = manual` here and merge, and then open an issue for getting an X display working in CI.  What do you think?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-blender/9#-NSgXdyOEflcmM6tPJk0:-NSlJMhR5_l9nYzZUy9L:b-896fix) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Works for me.
</blockquote></details>

Done.

___

**Pull request merged**
