### PR TITLE
Add server code, copied from TRI

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
My proposal is that we should merge this now, even though it lacks sufficient testing, comment clarity, etc. Loading of `*.blend` files probably doesn't work right either. After trying a few approaches though, I think it will be best to have a working prototype on the main branch, and then continue improving it from there.

---

Here's for forthcoming demo (#9) rendered using this code:

https://user-images.githubusercontent.com/17596505/230738201-847cced4-05ae-438b-bf66-8e469cb43f5e.mp4

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2)

### CODE REVIEW

**Review by zachfang — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-:-NSbRglv9dUAS27ywwwc:b-uwkowd)* status: 5 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`server.py` line 127 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbBNLQ1TmVI4dAdhHQ:-NSbBNLQ1TmVI4dAdhHR:b-kgclb0) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L127)):*
> ```Python
>         """
>         Renders the current scene with the given parameters. All the fields in
>         `params` are assumed to be validated beforehand except for `input_path`
> ```

nit. Both of them are not present in the new `RenderParams` dataclass.



_Code quote:_
```Python
        `params` are assumed to be validated beforehand except for `input_path`
        and `output_path`.
```
___
*[`server.py` line 335 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbHVr04fHcGrIMIRc1:-NSbHVr04fHcGrIMIRc2:b-8af6lf) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L335)):*
> ```Python
>             params = self._parse_params(flask.request)
>             buffer = self._render(params)
>             return flask.send_file(buffer, mimetype=f"image/png")
> ```

nit. Redundant f-string.
___
*[`server.py` line 354 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbMBLn0aOeNLEh5LvF:-NSbMBLn0aOeNLEh5LvG:blizik3) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L354)):*
> ```Python
>         # Compute a lookup table for known form field names.
>         param_fields = dict([
>             (x.name, x)
> ```

BTW. I was trying to understand how this dictionary is created. Seems like we create a list of tuples, and then use `dict()` to convert it to a dictionary.

Would it be easier to read as:
```
param_fields = {x.name: x for x in dc.fields(RenderParams)}
```



_Code quote:_
```Python
        param_fields = dict([
            (x.name, x)
            for x in dc.fields(RenderParams)
        ])
```
___
*[`server.py` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbQEKT15_ZkIu0Gc1D:-NSbQEKU93h1w0YNxfa2:b-obotnk) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L360)):*
> ```Python
> 
>         # Copy all of the form data into the result.
>         for name, value in request.form.items():
> ```

nit. To point out, we validate the file checksum before but not here anymore. Is that intended to drop? 



_Code quote:_
```Python
for name, value in request.form.items():
```
___
*[`server.py` line 373 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbPWpL7etZpuFukO8U:-NSbPWpL7etZpuFukO8V:b-78s91b) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L373)):*
> ```Python
>                     raise ValueError(f"Invalid literal for {name}")
>                 result[name] = value
>             elif type_origin == typing.Union:
> ```

BTW. My understanding is that this is for `typing.Optional[float]`. Maybe add a comment to make that clearer?



_Code quote:_
```Python
elif type_origin == typing.Union:
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2)* status: 1 unresolved discussion (waiting on @zachfang)

___
*[`server.py` line 127 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbBNLQ1TmVI4dAdhHQ:-NSfVOPv8Ew-CVdIZ1HF:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L127)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. Both of them are not present in the new `RenderParams` dataclass.
</blockquote></details>

Done.
___
*[`server.py` line 354 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbMBLn0aOeNLEh5LvF:-NSfVPLc-fbFmsZ2Y6wE:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L354)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. I was trying to understand how this dictionary is created. Seems like we create a list of tuples, and then use `dict()` to convert it to a dictionary.

Would it be easier to read as:
```
param_fields = {x.name: x for x in dc.fields(RenderParams)}
```
</blockquote></details>

Done.
___
*[`server.py` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbQEKT15_ZkIu0Gc1D:-NSfU0W64EcMaWfjzQkb:b-bk3l7a) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L360)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. To point out, we validate the file checksum before but not here anymore. Is that intended to drop? 
</blockquote></details>

Yes.  I think it's unlikely that http would let corrupted data through to us, so failing-fast in the event is a non-trivial amount of code that adds almost no value.
___
*[`server.py` line 373 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbPWpL7etZpuFukO8U:-NSfTzB84XrxNIn-bQQO:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L373)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. My understanding is that this is for `typing.Optional[float]`. Maybe add a comment to make that clearer?
</blockquote></details>

Done.

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`server.py` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbQEKT15_ZkIu0Gc1D:-NSfhM9-1qLV2d_Kqzxt:bjtwed0) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L360)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yes.  I think it's unlikely that http would let corrupted data through to us, so failing-fast in the event is a non-trivial amount of code that adds almost no value.
</blockquote></details>

In this case, should we note here or in the dataclass that `scene_sha256` is not used in this server or ignore it during parsing explicitly?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2)* status: 1 unresolved discussion (waiting on @zachfang)

___
*[`server.py` line 360 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2#-NSbQEKT15_ZkIu0Gc1D:-NSfp4rdBz74BKGK7YY7:b-58s9yx) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/efbb06af4162ed08da025caf98baf4c8e669f55d/server.py#L360)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

In this case, should we note here or in the dataclass that `scene_sha256` is not used in this server or ignore it during parsing explicitly?
</blockquote></details>

Definitely yes.  Done.

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/2)* status: :shipit: complete! all discussions resolved, LGTM from assignee zachfang (waiting on @jwnimmer-tri)

**Pull request merged**
