### PR TITLE
Platform review of examples

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The whitespace is to nudge Reviewable.
It will be reverted prior to merge.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for platform review per schedule, please.  (Waiting until Thursday is just fine.)

I added a blank line to the end of each file, so you have the relevant files in the File Matrix. Please expand the file in total and review it as-if the whole file was being newly committed for the first time.  I'll revert the blanks in the next push with any fixes.

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI gentle reping to make sure this is in your inbox.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: platform with small BTWs - nice!

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32#-:-NVjuAoq2gEZ_uye4gj7:b-f0s2x8)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`examples/ball_bin.py` line 190 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32#-NVju0Vq4yMZ5hF23vAX:-NVju0Vq4yMZ5hF23vAY:bkozlgl) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/b3a582d694e0dbecae11121e5b90aa363ce989ed/examples/ball_bin.py#L190)):*
> ```Python
>     if args.server:
>         logging.info("Starting drake-blender server")
>         server = _find_resource("__main__/server")
> ```

BTW Usage of `__main__` in Bazel respath context is unclear.

Is it possible to explicitly denote the workspace name in `WORKSPACE.bazel`?
___
*[`examples/test/ball_bin_test.py` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32#-NVjt77q75YOfaIWaYp4:-NVjt77rDQ8cYRAV7HBb:b-x82eac) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/b3a582d694e0dbecae11121e5b90aa363ce989ed/examples/test/ball_bin_test.py#L1)):*
> ```Python
> import os
> ```

BTW Should `bpy` code have SPDX indentifier? (even if already mentioned in root-level README?)
___
*[`examples/test/bpy_use_cycles.py` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32#-NVjt-Xa5Kh1kbJT8DbJ:-NVjt-Xa5Kh1kbJT8DbK:b-x82eac) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/b3a582d694e0dbecae11121e5b90aa363ce989ed/examples/test/bpy_use_cycles.py#L1)):*
> ```Python
> bpy.context.scene.render.engine = "CYCLES"
> ```

BTW Should `bpy` code have SPDX indentifier? (even if already mentioned in root-level README?)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32)* status: 1 unresolved discussion (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`examples/ball_bin.py` line 190 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32#-NVju0Vq4yMZ5hF23vAX:-NVk3GbRA8VdXOb1qLaw:b-83sjoh) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/b3a582d694e0dbecae11121e5b90aa363ce989ed/examples/ball_bin.py#L190)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Usage of `__main__` in Bazel respath context is unclear.

Is it possible to explicitly denote the workspace name in `WORKSPACE.bazel`?
</blockquote></details>

Nice!
___
*[`examples/test/ball_bin_test.py` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32#-NVjt77q75YOfaIWaYp4:-NVk2FAtBpasaNghBqpM:b-2p4z9n) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/b3a582d694e0dbecae11121e5b90aa363ce989ed/examples/test/ball_bin_test.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Should `bpy` code have SPDX indentifier? (even if already mentioned in root-level README?)
</blockquote></details>

I think not.  These files are MIT-0 on their own (if someone were to copy-paste from them, but calling the VTK server instead of vpy server, they would no longer be subject to GPL).

Ah.  But the MIT-0 is missing, isn't it?  Working...

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI (waiting on @EricCousineau-TRI)

___
*[`examples/test/ball_bin_test.py` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32#-NVjt77q75YOfaIWaYp4:-NVk3y8a8eXDMA_y69Fu:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/b3a582d694e0dbecae11121e5b90aa363ce989ed/examples/test/ball_bin_test.py#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think not.  These files are MIT-0 on their own (if someone were to copy-paste from them, but calling the VTK server instead of vpy server, they would no longer be subject to GPL).

Ah.  But the MIT-0 is missing, isn't it?  Working...
</blockquote></details>

Done.

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/32)* status: :shipit: complete! all discussions resolved, LGTM from assignee EricCousineau-TRI (waiting on @jwnimmer-tri)

**Pull request merged**
