### PR TITLE
Add black autoformatter and linter

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards #25.

I am not a huge fan of `black`'s choices personally, but I think having an autoformatter is more important.  Once we have the linter enabled everywhere, then if people are interested they are welcome to try playing with its config knobs to find a style we like better.  My vote is to turn it on first, and play with config knobs second.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/36)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 8 of 14 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/36)* status: needs at least one assigned reviewer (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Anyone want to assign and badge this one?

I know Zach is personally a fan of `black`, so I don't think we need to wait for his OK here.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@SeanCurtis-TRI :LGTM:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/36#-:-NVgUPxD4nQBHV4b1n6s:bm2rfw7)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I may not have merge abilities -- or github is just being cranky. Github status seems content; I'm chalking it up to permissions.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/36#-:-NVgUWKBCVKvCIdm-z88:b-avubpm)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
That's weird.  `SeanCurtis-TRI` is part of https://github.com/orgs/RobotLocomotion/teams/tri and that team has Write access so should be able to merge.

**Review by SeanCurtis-TRI — COMMENTED** [review]
Hmmm...it knew who I was well enough to allow me to self assign, but merge. I had to log in again, but this time I bet it'll work.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/36#-:-NVgY2248rN3YAaggjPS:bn69d0a)* status: :shipit: complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI (waiting on @jwnimmer-tri)

**Comment by SeanCurtis-TRI** [comment]
Nope:

`Unable to merge branch: GitHub error 404 on PUT https://api.github.com/repos/RobotLocomotion/drake-blender/pulls/36/merge: Not Found`

**Comment by jwnimmer-tri** [comment]
Is that using the Reviewable UI, or the page at https://github.com/RobotLocomotion/drake-blender/pull/36 ?

**Comment by SeanCurtis-TRI** [comment]
Reviewable.

**Comment by SeanCurtis-TRI** [comment]
Worked in GH.

**Comment by zachfang** [comment]
I was catching up with the merged PRs and noticed a [minor thing](https://github.com/RobotLocomotion/drake-blender/blob/main/server.py#L464):
```
'`bpy.context.scene.render.engine = "EEVEE"` (with no backticks). '
```
The backticks were removed by the formatter, so we can eliminate the `(with no backticks)` part.
(I am also not sure if it's worth a one-liner PR or should be lumped into other fixes.)

**Comment by jwnimmer-tri** [comment]
The backslashes were removed, but the backticks are still there.

**Pull request merged**
