### PR TITLE
[tools] Finish porting to bzlmod

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Specifically, respell the "download buildifier release binaries from github" into something bzlmod is happy with.

While we're here, also remove custom upgrade scripting for `bazel`. Dependabot handles that upgrade automation for us now (see e.g. #100).

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/108)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for review, please?

FYI @rpoyner-tri

**Review by zachfang — COMMENTED** [review]
:lgtm: I will catch up on bzlmod a bit.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/108#-:-ODl3ecHBazfPxXnxiw1:bsa46ax)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tools/upgrade_helper.py` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/108#-ODl3F286s-6oV_Bnmg3:-ODl3F290F2z6R1Xy8UY:b-2nz0ep) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/47683ad5a7fb573ff1083a35f5cd88f0f6971062/tools/upgrade_helper.py#L48)):*
> ```Python
>     """Overwrites ``.bazelversion`` with the new version of bazel."""
>     with open(".bazelversion", "w", encoding="utf-8") as f:
>         f.write(f"{new}\n")
> ```

nit. I assume these two functions can be removed as well as they are only called by `_upgrade_bazel()`.



_Code quote:_
```Python
def _get_current_bazel_version() -> str:
    """Parses ``.bazelversion`` for the old version of bazel."""
    with open(".bazelversion", encoding="utf-8") as f:
        lines = f.read().splitlines()
    (line,) = lines
    return line.strip()


def _write_bazel_version(new):
    """Overwrites ``.bazelversion`` with the new version of bazel."""
    with open(".bazelversion", "w", encoding="utf-8") as f:
        f.write(f"{new}\n")
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/108)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee zachfang (waiting on @zachfang)

___
*[`tools/upgrade_helper.py` line 48 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/108#-ODl3F286s-6oV_Bnmg3:-ODl4MOoB8EgCP2ckA1Y:buo41x7) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/47683ad5a7fb573ff1083a35f5cd88f0f6971062/tools/upgrade_helper.py#L48)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

nit. I assume these two functions can be removed as well as they are only called by `_upgrade_bazel()`.
</blockquote></details>

Right!  Thanks.

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/108)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee zachfang (waiting on @jwnimmer-tri)

**Pull request merged**
