### PR TITLE
[workspace] Add upgrade automation for all remaining dependencies

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/60)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please.
+@ggould-tri for platform review per schedule, please.

**Comment by jwnimmer-tri** [comment]
\CC @zachfang @SeanCurtis-TRI FYI

**Review by SeanCurtis-TRI — COMMENTED** [review]
I'll give this my own :LGTM: if you want to play with feature review assignments.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/60#-:-NaeDsD3AgeLIVRI7BDF:bmaydrp)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri,ggould-tri (waiting on @ggould-tri, @jwnimmer-tri, and @rpoyner-tri)

___
*[`bazel` line 21 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/60#-NaeBrRa0fXdp2lJ8Csx:-NaeBrRa0fXdp2lJ8Csy:b-qrf9xs) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/571c643a7c988a938255b8e0ebd0a5630767a8ae/bazel#L21)):*
> ```
> import urllib.request as request
> 
> # The pinned version and checksum of bazekisk.
> ```

nit typo



_Suggestion:_
```
bazelisk
```

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/60)* status: LGTM missing from assignee rpoyner-tri (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Ping @rpoyner-tri for platform review, please.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/60#-:-Ncx3wET2FW4DL1EnfnM:bnfp4nl)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tools/upgrade_helper.py` line 38 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-blender/60#-Ncx0zvB9Yf5cv1blO4E:-Ncx0zvB9Yf5cv1blO4F:bb7phvt) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/c94c9f8c46c6d8ff7c0678cf4da05c9b3e600032/tools/upgrade_helper.py#L38)):*
> ```Python
> 
> def _get_current_bazel_version() -> str:
>     """Parses ``.bazelrc``for the old version of bazel."""
> ```

typo



_Suggestion:_
```Python
``.bazelrc`` for
```

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/60)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri,SeanCurtis-TRI (waiting on @jwnimmer-tri)

**Pull request merged**
