### PR TITLE
Add requirements_upgrade script

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Use it to bump all requirements to latest.
This happens to fix a Drake version shear bug.

+@rpoyner-tri for both reviews per schedule, please.

\CC @zachfang @sammy-tri FYI

Relates #42.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/47)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/47)* status: LGTM missing from assignee rpoyner-tri (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/47#-:-NW8fxfSEYXKpzv4ifKC:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignee rpoyner-tri (waiting on @jwnimmer-tri)

**Comment by zachfang** [comment]
[Question] Is this `requirements_upgrade.sh` the script to set up all the dependencies when a user fresh-clones `drake-blender` (similar to what `install_prereq.sh` in `drake`)?

**Comment by jwnimmer-tri** [comment]
No, it's different.  It's for project maintainers to reflect the newest dependencies (e.g., blender, flask, or drake versions) back into the lockfiles in git.

This is akin to https://github.com/RobotLocomotion/drake/tree/master/tools/workspace#semi-automated-monthly-upgrades.

There are no `install_prereqs` for this project.  Either the user runs `./bazel run //:server` which will fetch all of the dependencies automatically, or the user runs `python3 server.py` from their own virtual environment that already has flask and bpy.

**Pull request merged**
