### PR TITLE
Add autofix suggestion when lint tools fail

### LINKED ISSUE #49: Improve lint failure suggestions
When a lint test fails, it would be nice to tell developers to run `fix_lint.sh`.  They should never need to fix lint by hand, but it's not always obvious what to do.

We have docs at https://github.com/RobotLocomotion/drake-blender#linting but its easy to miss.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This requires adding wrapped main functions, and that's enough new mass to push me to move our developer tools into a new sub-directory.

Closes #49.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/50)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please (especially of UX by testing locally).

+@rpoyner-tri for platform review, please (and feature-ish review of build practices).

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm: nice to move a lot of gunk out of the top-level BUILD file.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/50#-:-NWDnnQTDmONe-83VS_e:bwp0cbi)* status: LGTM missing from assignee zachfang (waiting on @zachfang)

**Review by zachfang — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/50#-:-NWG3MnG1UxLZA2lkv2f:bg7igkv)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`tools/isort_main.py` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/50#-NWG31dWDiBoIOHuoCuZ:-NWG31dWDiBoIOHuoCu_:bkpr4ol) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/2dc6440533f88d83730a352ca9fcca810660b574/tools/isort_main.py#L10)):*
> ```Python
>         _isort_main()
>     except SystemExit as e:
>         if (e.code or 0) != 0:
> ```

BTW. Why couldn't we do `if e.code != 0` directly?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/50)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri,zachfang (waiting on @rpoyner-tri)

___
*[`tools/isort_main.py` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/50#-NWG31dWDiBoIOHuoCuZ:-NWI7Oor784T1Mo1qk1t:bolkbbf) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/2dc6440533f88d83730a352ca9fcca810660b574/tools/isort_main.py#L10)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Why couldn't we do `if e.code != 0` directly?
</blockquote></details>

Sometimes `e.code` can be `None`, which we would like to treat as `0`.

I'd originally written that in a compact way typical of perl programming conventions, but for python we definitely should spell it out more clearly.

**Pull request merged**
