### PR TITLE
Add build infrastructure

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
```console
jwnimmer@call-cps:~/drake-blender$ ./bazel run :server
INFO: Invocation ID: d08bc48f-fc80-4656-b162-e409f9f40207
INFO: Analyzed target //:server (25 packages loaded, 179 targets configured).
INFO: Found 1 target...
Target //:server up-to-date:
  .bazel/bin/server
INFO: Elapsed time: 0.614s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: .bazel/bin/server

Warning! '/media/sdb/cache/bazel/_bazel_jwnimmer/701a9951861d73d65aa9eb0ed6d53787/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/requirements_bpy/site-packages/bpy/3.4/scripts/startup/bl_app_templates_system/__init__.py' has no register function, this is now a requirement for registerable scripts
Traceback (most recent call last):
  File "/media/sdb/cache/bazel/_bazel_jwnimmer/701a9951861d73d65aa9eb0ed6d53787/execroot/__main__/bazel-out/k8-fastbuild/bin/server.runfiles/__main__/server.py", line 10, in <module>
    raise NotImplementedError()
NotImplementedError
```

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/1)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang are you up for feature review?

**Review by zachfang — COMMENTED** [review]
:lgtm: I am far from a Bazel expert, but I followed the comments and assume most of the bootstrapping build files are fairly standard.

> Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/1#-:-NQXhHHi4ZSOj4EsjX1A:b-12cpny)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`LICENSE.TXT` line 3 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-blender/1#-NQXbt01BEuWX2o5jMWE:-NQXbt01BEuWX2o5jMWF:b-8xmefe) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/9595d0414b3ad937264d1cf4149d48207b700b8b/LICENSE.TXT#L3)):*
> ```
> SPDX-License-Identifier: BSD-2-Clause
> 
> All components of Drake are licensed under the BSD-2-Clause License
> ```

BTW. Just to confirm if this should be `Drake`, `drake-blender`, or something similar?



_Code quote:_
```
Drake
```

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/1)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @zachfang)

___
*[`LICENSE.TXT` line 3 at r2](https://reviewable.io/reviews/RobotLocomotion/drake-blender/1#-NQXbt01BEuWX2o5jMWE:-NQXk24ODGppT3C-EmE4:bx7jcx8) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/9595d0414b3ad937264d1cf4149d48207b700b8b/LICENSE.TXT#L3)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. Just to confirm if this should be `Drake`, `drake-blender`, or something similar?
</blockquote></details>

Done.

Yeah, originally I was thinking of saying "Drake" in the whole family of drake projects, no matter which one it was.  It's probably better to be specific, though.

**Review by zachfang — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/1)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> I followed the comments ...

Great!

> ... and assume most of the bootstrapping build files are fairly standard.

More or less, yeah.  The `bazel` auto-bootstrapper script is a bit novel, but the rest is pretty boring.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Pull request merged**
