### PR TITLE
[examples] Drop CI requirement for DISPLAY

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See also https://github.com/RobotLocomotion/drake/pull/22197 for related changes.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/95)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for reviews, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/95#-:-OBzl6wIA43o4Uzn8RM2:bmxilld)* status: 1 unresolved discussion (waiting on @jwnimmer-tri)

___
*[`examples/ball_bin.yaml` line 65 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/95#-OBzkzweAq66rOwzOvz2:-OBzkzweAq66rOwzOvz3:b-4ebvp2) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/866ddcaeee901a2b3ccc9b30986339c799c05a53/examples/ball_bin.yaml#L65)):*
> ```YAML
>     renderer_class: !RenderEngineVtkParams
>       backend: EGL
>     # For `show_rgb: True` you must also set the `backend: GLX` on prior line.
> ```

BTW Given this is used in CI, a further note indicating that this change should only be for local invocations of the test and it should never be commited as GLX?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/95)* status: 1 unresolved discussion (waiting on @SeanCurtis-TRI)

___
*[`examples/ball_bin.yaml` line 65 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-blender/95#-OBzkzweAq66rOwzOvz2:-OBznO7w4mgwric9kvuG:b-5ibfc) ([raw file](https://github.com/RobotLocomotion/drake-blender/blob/866ddcaeee901a2b3ccc9b30986339c799c05a53/examples/ball_bin.yaml#L65)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Given this is used in CI, a further note indicating that this change should only be for local invocations of the test and it should never be commited as GLX?
</blockquote></details>

I want to keep this file aimed at users as its audience (not us maintainers), but I think I found a way to clarify the comment that helps the users, too.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/95)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignee SeanCurtis-TRI (waiting on @jwnimmer-tri)

**Pull request merged**
