### PR TITLE
Port to use bzlmod and hermetic Python

### LINKED ISSUE #67: Switch to bzlmod

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
See https://bazel.build/external/module for docs about `bzlmod`.  The `WORKSPACE` mechanism in Bazel will be deprecated around the end of this year, and removed about a year (or a little more) after that.  Porting some of our smaller projects like this one to `bzlmod` is good practice for working the same on Drake (https://github.com/RobotLocomotion/drake/issues/20731).

Closes #67.

---

Respell `WORKSPACE.bazel` into `MODULE.bazel` + `WORKSPACE.bzlmod`. For now, this means that our skylark external dependencies (like `rules_python`) are not upgraded by `tools/upgrade.sh` -- there's a TODO instead.  (My expectation is that after this PR lands, the `@renovatebot` will automatically handle it for us.)

Switch from the Ubuntu Python interpreter to a Bazel one (downloaded as an external). Since any given version of Blender only works with one specific version of CPython, this will make it easier to stay in sync long-term. This also lets us drop the `unittest_path_cleaner` hack to avoid test pollution from Ubuntu libraries.

Switch to using a `pip()` helper macro to specify the pip deps for our programs. The old long-hand spellings don't work with bzlmod.

Switch to `rules_python` runfiles instead of `bazel_tools` runfiles (ala https://github.com/RobotLocomotion/drake/pull/21331).

Add `test/BUILD.bazel` as a sub-package; writing out all of the test rules in the top-level `BUILD.bazel` was too much clutter.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/76)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang and +@SeanCurtis-TRI for review, please.

\CC @rpoyner-tri FYI

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 2 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/76)* status: LGTM missing from assignees SeanCurtis-TRI,zachfang (waiting on @SeanCurtis-TRI and @zachfang)

**Review by zachfang — COMMENTED** [review]
:lgtm: 

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/76#-:-Ny71dqi9veW-CzudmVH:bg7igkv)* status: LGTM missing from assignee SeanCurtis-TRI (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM: The changes seem consistent with the documentation, but the bazel details go beyond my level of comprehension. So, take the stamp for what it's worth.

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-blender/76#-:-NyLL-X3-6NNO0PkBWTC:brwtz0n)* status: <span>:shipit:</span> complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI,zachfang (waiting on @jwnimmer-tri)

**Pull request merged**
